<?php
function xlsx_col($n){$s='';while($n>0){$n--; $s=chr(65+($n%26)).$s;$n=intdiv($n,26);}return $s;}
function xlsx_escape($v){return htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');}
function xlsx_shared_strings($rows){$map=[];$strings=[];foreach($rows as $row)foreach($row as $v){$v=(string)$v;if(!isset($map[$v])){$map[$v]=count($strings);$strings[]=$v;}}return [$map,$strings];}
function xlsx_csv_fallback($filename,$rows){header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename='.preg_replace('/[^A-Za-z0-9_-]/','_',pathinfo($filename,PATHINFO_FILENAME)).'.csv');$o=fopen('php://output','w');foreach($rows as $r)fputcsv($o,$r);fclose($o);}
/**
 * Chemin d'un fichier .xlsx temporaire inscriptible.
 * Sur hébergement mutualisé (InfinityFree), sys_get_temp_dir() renvoie
 * /home/tmp, HORS open_basedir : tempnam() échoue alors et ZipArchive::open()
 * lève une ValueError => erreur 500. app_temp_file() (functions.php) choisit
 * d'abord un dossier interne au projet (uploads/tmp), non servi par le web.
 */
function xlsx_temp_file(){$path=function_exists('app_temp_file')?app_temp_file('xlsx'):'';if($path!=='')return $path;foreach([sys_get_temp_dir(),'/tmp'] as $dir){if($dir===''||!@is_writable($dir))continue;$f=rtrim($dir,'/\\').'/xlsx_'.bin2hex(random_bytes(8)).'.tmp';if(@file_put_contents($f,'')===0)return $f;}return '';}
function create_xlsx($filename,$sheetName,$rows){
 if(!class_exists('ZipArchive')){xlsx_csv_fallback($filename,$rows);return;}
 [$map,$strings]=xlsx_shared_strings($rows);$sheet='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';
 foreach($rows as $ri=>$row){$r=$ri+1;$sheet.='<row r="'.$r.'">';foreach(array_values($row) as $ci=>$v){$cell=xlsx_col($ci+1).$r;$sheet.='<c r="'.$cell.'" t="s"><v>'.$map[(string)$v].'</v></c>';}$sheet.='</row>';}$sheet.='</sheetData></worksheet>';
 $shared='<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="'.count($strings).'" uniqueCount="'.count($strings).'">';foreach($strings as $str)$shared.='<si><t>'.xlsx_escape($str).'</t></si>';$shared.='</sst>';
 $tmp=xlsx_temp_file();$zip=new ZipArchive();
 if($tmp===''||$zip->open($tmp,ZipArchive::OVERWRITE)!==true){xlsx_csv_fallback($filename,$rows);return;}$zip->addFromString('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/></Types>');$zip->addFromString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');$zip->addFromString('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="'.xlsx_escape($sheetName).'" sheetId="1" r:id="rId1"/></sheets></workbook>');$zip->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/></Relationships>');$zip->addFromString('xl/worksheets/sheet1.xml','<?xml version="1.0" encoding="UTF-8"?>'.$sheet);$zip->addFromString('xl/sharedStrings.xml','<?xml version="1.0" encoding="UTF-8"?>'.$shared);$zip->close();header('Content-Type:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition:attachment; filename="'.basename($filename).'"');header('Content-Length:'.filesize($tmp));readfile($tmp);@unlink($tmp);exit;
}
